- name: "install head packages"
  become: true
  pacman:
    name: "{{ item }}"
  with_items:
    - alsa-utils
    - xorg
    - xorg-xinit
    - xorg-xrdb
    - arandr
    - rxvt-unicode
    - i3-wm
    - dmenu
    - i3status
    - i3lock
    - ttf-inconsolata
    - gcc
    - xf86-video-intel

- name: "configure x11 keyboard"
  become: true
  copy:
    src: 99-keyboard.conf
    dest: /etc/X11/xorg.conf.d/

- name: "configure x11 touchpad"
  become: true
  copy:
    src: 99-synaptic-touchpad.conf
    dest: /etc/X11/xorg.conf.d/

- name: "copy xinitrc"
  copy:
    src: xinitrc
    dest: ~/.xinitrc

- name: "copy Xresources"
  copy:
    src: Xresources
    dest: ~/.Xresources

- name: "configure i3"
  copy:
    src: i3
    dest: ~/.config

- name: "configure i3status"
  copy:
    src: i3status
    dest: ~/.config

- name: "unmute alsa"
  command: amixer sset Master unmute
  become: true

- name: "permission to change brightness"
  become: true
  user:
    name: "{{ lookup('env','USER') }}"
    groups: video
    append: true

- name: "brightness udev rule"
  become: true
  copy:
    src: backlight.rules
    dest: /etc/udev/rules.d/backlight.rules

- name: "configure"
  become: true
  copy:
    src: 20-intel.conf
    dest: /etc/X11/xorg.conf.d/

